### ISSUE TITLE
Hirondelle node is out of date

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/Marble-node-registry#22]
The Hirondelle node does not provide `/services` or `/version` endpoints and so cannot be queried by the registry update script.

Solution: update the Hirondelle stack to at least version [1.26.7](https://github.com/bird-house/birdhouse-deploy/releases/tag/1.26.7) of [birdhouse-deploy](https://github.com/bird-house/birdhouse-deploy)

**Comment by fmigneault** [comment]
@matprov
Relates to https://crim-ca.atlassian.net/browse/DAC-572

**Comment by matprov** [comment]
@mishaschwartz Hirondelle is now updated with version 1.27.1. Autodeploy was blocked since a manual change has been made on the repo.

**Comment by mishaschwartz** [comment]
The registry update scripts have now updated the registry with the details from the Hirondelle node.
