### ISSUE TITLE
A "last_online" entry for nodes?

### ISSUE THREAD

**Issue by dchandan** [DACCS-Climate/Marble-node-registry#24]
Should we add a `last_online` entry (or something like that) in the node registry to track how long it has been since a node has been offline?

**Comment by dchandan** [comment]
@mishaschwartz @fmigneault

**Comment by mishaschwartz** [comment]
We have that since the `last_updated` field is only updated if the node is online

**Comment by dchandan** [comment]
Oh that's good!
