### ISSUE TITLE
Proposed new format

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/Marble-node-registry#3]
- Add "date_added" field (iso format datetime) in node_registry.json (indicates when the node was added to the network)
- Remove "deployed since" from node_info.json
- Remove "location" (that info can be added to affiliation if needed)
- Replace "administrators" and "support_contact" with "contact" 
- Add "date_updated" field (iso format datetime) in node_info.json (indicates when the node info was last changed)
- Add "available" field (boolean) in node_info.json (indicates whether the node responds when updating info)
- Replace "capabilities" field with "services" (list of services available at a given node and the relative path)

node_registry.json
```json
{
  "name": {"url": "example.com", "date_added": "....."}
}
```

node_info.json
```json
{
    "name":{
        "affiliation": ".....",
        "services": {
            "thredds": "/thredds",
            "catalog": "/stac",
            "jupyter": "/jupyter/hub"
        },
        "date_updated": "........",
        "contact": "somesupport@example.com"
    },
}
```

**Comment by fmigneault** [comment]
Extra proposals. 

I've often seen the following in APIs to report external references. 
This is more machine-readable because `"/<path>"` are usually relative to the location providing the contents, not another URL in the returned JSON. The `type` also helps machines know what to expect if following those links. Mandatory fields are only `href` and `rel`, and they can be mapped directly to an API's `Link` header.
```json
{
  "links": [
    {"href": "<url>", "rel": "<identifier>", "title": "<title>", "type": "<IANA media-type>"},
    {"href": "<url>", "rel": "<identifier>", "..."}
  ]
}
```

Also, is there any advantage to split `node_registry.json` and `node_info.json`? It would be easier to have everything bundled together.

**Comment by mishaschwartz** [comment]
@fmigneault the idea is that node_registry.json is static and only ever updated manually. node_info.json is dynamic and updated regularly by polling the network manager endpoints provided by each node in the network.

We could combine them but we kept them separate initially to differentiate between their purposes.

I'm happy to add any additional fields to the json that will be useful for future development, so I like your links suggestion.

**Comment by mishaschwartz** [comment]
We should keep location but keep it more machine readable (geo-json? https://geojson.org/) so that it can be plotted onto a map in some frontend application.

**Comment by mishaschwartz** [comment]
- rename `date_updated` with `last_updated`
- add `version` to the info json (showing the version number of the stack)
- make `available` field a string (not a boolean) so that we can expand the values beyond yes/no in the future
- rename `available` to `status` (current values: online/offline)
- node info should also include `url` and `date_added`
- add `logo_url` so that the organization's logo can be displayed on the frontend

**Comment by fmigneault** [comment]
@mishaschwartz 
> geo-json?

Maybe https://schema.org/location. It has a sub-field [`geo`](https://schema.org/geo) for GeoJSON, but allows more human readable details as well.

I'd suggest trying to map as many items as possible with JSON-LD and schema.org types.

**Comment by mishaschwartz** [comment]
We really just want to be able to plot the location of the nodes on a map (like this: https://esgf-node.llnl.gov/projects/esgf-llnl/) so latitude/longitude is fine for now. I don't want to over-engineer this at the moment and we can always extend it later if we have other use-cases.
